### ISSUE TITLE
Firebase Google Sign In User Authentication on IOS issues

### ISSUE THREAD

**Issue by Ryan-Korteway** [googlesamples/io2015-codelabs#109]
Hello,

I cannot tell if it is my emulator not sending something all the way through or firebase not getting updated properly because I am in the last stages of this course: https://codelabs.developers.google.com/codelabs/firebase-auth-ios/index.html?index=..%2F..%2Findex#0

And at the end of page 6, I sign in with my google account information and I allow the login, it returns me to my app, but no pop up of congratulations and I do not see my account on my firebase backend despite my phone receiving not one but two "New Login on Safari" emails which are me logging into the app with the google sign in page in safari.

So it would appear that my login with google itself was successful enough but there seems to be some disconnect between google, firebase, and or my app. I am getting this recurring issue in xcode about there being an error/inability to connect to a PID of a random number.

Unless I missed something or destroyed the spacing while I was cleaning up the code after an ugly copy/paste, my sign in method should be identical to the code in the lab itself:

-(void)signIn:(GIDSignIn *) signIn didSignInForUser:(GIDGoogleUser *)user
    withError:(NSError *)error {
    if(error == nil) {
        GIDAuthentication *authentication = user.authentication;
        FIRAuthCredential *credential = [FIRGoogleAuthProvider
                                credentialWithIDToken:authentication.idToken
                                    accessToken:authentication.accessToken];
        
    [[FIRAuth auth] signInWithCredential:credential
        completion:^(FIRUser * _Nullable user, NSError * _Nullable error) {
            
            if(user){
                NSString *welcomeMessage = [NSString stringWithFormat:
                @"Welcome to Firebase, %@", user.displayName];
                            
                NSString *alertTitle = @"Firebase Auth Codelab";
                            
                UIAlertController *alertController = [UIAlertController
                                        alertControllerWithTitle:alertTitle
                                        message:welcomeMessage
                                preferredStyle:UIAlertControllerStyleAlert];
                            
                UIAlertAction *okAction = [UIAlertAction
                        actionWithTitle:NSLocalizedString(@"OK", @"OK action")
                            style:UIAlertActionStyleDefault handler:^(UIAlertAction *action)
                                        {
                                            NSLog(@"OK action");
                                        }
                                           ];
                                          
                [alertController addAction:okAction];
                [self presentViewController:alertController
                                animated:YES completion:nil];
                                          
                _SignInButton.enabled = false;
                _SignOutButton.enabled = true;
                        }
            }];
    } else {
        NSLog(@"%@", error.localizedDescription);
    }
}

**Comment by Ryan-Korteway** [comment]
There was one change xcode made by suggestion so i undid that and I am now trying it again.

**Comment by Ryan-Korteway** [comment]
Still getting the same results. Login portal opens in safari, I successfully log in, I receive the emails about logging in, but I still do not receive the pop up about logging in correctly and I have no logged in users according to my firebase backend.

**Comment by Ryan-Korteway** [comment]
From my debugging, if(user) is not executing its block so that explains why I am getting no pop up etc but it still does not explain why the sign in button freezes and does not allow me to try and sign in again. It also does not explain why the firebase stuff is not going through and adding my user to the backend.

So i guess the bug is in the if(user) conditional and the call of [[FIRAuth auth] signInWithCredentials.... is not going through or something.

PS sorry if this is all sounding ridiculous and unnecessary. I am only just getting back into IOS development after having only taken a 2 week crash course ~6+ months ago.

**Comment by ToddKerpelman** [comment]
Hmmm... so I'm just confirming, you are getting to the point where this `didSignInForUser` method is getting called? It's just that user is nil? 

If that's the case, would you mind adding a  `} else { NSLog(@"Error: %@", error.localizedDescription) }` bit after your if (user) conditional? Perhaps there's an error there we're overlooking...

**Comment by Ryan-Korteway** [comment]
Yeah turns out my google plist file that I downloaded was missing the web apikey so a redownload of that was all i needed. 

Sent from my ASUS

-------- Original Message --------

**Comment by ToddKerpelman** [comment]
Okay. That's easy enough. Closing this bug. :)
