### ISSUE TITLE
AndroidPay codelab - BuyButtonText.BUY_WITH doesn't exist

### ISSUE THREAD

**Issue by saguinav** [googlesamples/io2015-codelabs#13]
I guess it should replaced by BuyButtonText.BUY_WITH_GOOGLE

**Comment by intelliot** [comment]
+1, I also encountered this issue.

**Comment by intelliot** [comment]
At #io15, Sam Stern indicated that `BUY_WITH` is a new constant that will be coming with Android Pay. The current constants, `BUY_WITH_GOOGLE` and `BUY_NOW`, can be used for the Codelab, but they will show Google Wallet branding. The branding will be updated to Android Pay in the future.

**Comment by samtstern** [comment]
Moving to BUY_NOW, thanks!
