### ISSUE TITLE
Get Started with Android Pay: Minor typos

### ISSUE THREAD

**Issue by intelliot** [googlesamples/io2015-codelabs#15]
On `Step 13. Request the Full Wallet`, the sentence at the end of the page ends with a comma `,` which implies that there should be more text (or maybe it should be a period `.`)

On `16. Add a Payment Processor (Optional)` this sentence uses the word "chare":

> When you receive the FullWallet object, you can use the following code snippet to extract a token that you can use with the Stripe API to chare the customer:

**Comment by samtstern** [comment]
Fixing, thank you!
