### ISSUE TITLE
Get Started with Android Pay: addPaymentMethodTokenizationParameters should start with set

### ISSUE THREAD

**Issue by intelliot** [googlesamples/io2015-codelabs#16]
addPaymentMethodTokenizationParameters -> setPaymentMethodTokenizationParameters

Also, `stripe:version` is required. Otherwise you'll get error 404 (note for other developers: google for `WalletConstants` to find out what the number means)

`2015-05-29` appears to work as an example stripe:version. At the time of this writing, `2015-04-07` is latest.

**Comment by samtstern** [comment]
Thanks for the report, fixing it!
