### ISSUE TITLE
Missing instructions to include GooglePlayGames causing compilation error

### ISSUE THREAD

**Issue by colinexl** [googlesamples/io2015-codelabs#18]
In the Trigger Achievements section for DroidController.cs, instructions did not mention using GooglePlayGames import and will cause a compilation error.

**Comment by claywilkinson** [comment]
Thanks for the feedback! we'll update it.

**Comment by yakauk** [comment]
googleplaygame

**Comment by claywilkinson** [comment]
Updated.
