### ISSUE TITLE
cloud-nodejs: Use global-level configuration

### ISSUE THREAD

**Issue by jgeewax** [googlesamples/io2015-codelabs#21]
In the cloud-nodejs codelab, we ask people to configure things twice with the same values (https://github.com/googlesamples/io2015-codelabs/blob/17c4f36d3182a20798c6854234229a31f9d8c377/cloud-nodejs/step-3-book-cover-images/books.js#L7)

Might be worthwhile to do this at the parent level:

Old:

```javascript
  var gcloud = require('gcloud');

  var dataset = gcloud.datastore.dataset({
    projectId: config.projectId,
    keyFilename: config.keyFilename
  });

  var storage = gcloud.storage({
    projectId: config.projectId,
    keyFilename: config.keyFilename
  });
```

New

```javascript
  var gcloud = require('gcloud')({
    projectId: config.projectId,
    keyFilename: config.keyFilename
  });

  var dataset = gcloud.datastore.dataset();
  var storage = gcloud.storage();
```

**Comment by hostirosti** [comment]
Thank you for the tipp and sorry for the delay in integrating it into the codelab.
