### ISSUE TITLE
Unity-Cardboard tutorial errors

### ISSUE THREAD

**Issue by linojon** [googlesamples/io2015-codelabs#27]
**Step 4**
***Add cardboard mode to the main menu scene***
Sometimes the Component > Cardboard menu is not present. Saving, closing Unity and reopening fixes it.

**Step 5**
***Handle VR pointing and clicking***
must check the "Vr Mode Only" checkbox (or the menu buttons flicker and are not selectable)

***Associate the click event with the script***
In the scene hierarchy, select the buttonCardboard object(under Canvas/Panel) ."

should refer to cardboardButton

**Step 7**
Need to add CardboardModeMgr script to Canvas so it starts in the right mode (and set the Main Camera on it). Otherwise it always starts in VR mode regardless of the PlayerPrefs.

**Comment by linojon** [comment]
Also Step 3, the numbered lists should be one number for the subject the others regular bullet items not numbered

**Comment by claywilkinson** [comment]
Thanks for the feedback!
