### ISSUE TITLE
Cardboard Unity - UIButton onClick not working on phone

### ISSUE THREAD

**Issue by BalbretOK** [googlesamples/io2015-codelabs#31]
Hi,

I encountered a problem with the UIButton (start and Cardboard Mode) when I deployed the app into my Android phone. In normal mode, the button is working fine, but when I change it to Cardboard mode, the button doesnt seem to work anymore. I press the trigger button or touch the screen does not have any effect thus making me stuck in the main menu in Cardboard mode. Any idea why?

The button works perfectly fine in preview when I run the scene from Unity.

**Comment by ToddKerpelman** [comment]
I had a similar issue in my (completely different) app -- it went away when it turned on the "Tap Is Trigger" option in the Cardboard Main object. Does that work for you?

**Comment by BalbretOK** [comment]
@ToddKerpelman I didn't try that. But after countless hours of debugging I've found that it because in the GazeInputModule script, the gameobject input is pointing is actually at the Text GameObject of the button instead of the Button itself. Thus I modified the code so that the gameobject is pointing to the parent of the Text GameObject (i.e. the Button) and then it works like a charm. 

Though I have no idea if this is a bug or the actual implementation is meant to be like that...

**Comment by niguerrac** [comment]
@BalbretOK hi, how u solved problem? u can show GazeInputModule code?

**Comment by BalbretOK** [comment]
@niguerrac the code below :) 

    private void HandleTrigger() {
	bool triggered = Cardboard.SDK.Triggered
		|| (!Cardboard.SDK.TapIsTrigger && Input.GetMouseButtonDown(0))
		|| (!Cardboard.SDK.TapIsTrigger && screenTouched); 
	if (!triggered) {
		return;
	}
	var go = pointerData.pointerCurrentRaycast.gameObject;
	// go points to the text object instead of the button
	// get the parent object which is the button
	GameObject btn = go.transform.parent.gameObject;
	// check if button is not null to avoid Null exception
	if (btn != null)
		go = btn;

	if (go == null)
		return;

    // Send pointer down event.
    pointerData.pressPosition = pointerData.position;
    pointerData.pointerPressRaycast = pointerData.pointerCurrentRaycast;
    pointerData.pointerPress =
        ExecuteEvents.ExecuteHierarchy(go, pointerData, ExecuteEvents.pointerDownHandler)
        ?? ExecuteEvents.GetEventHandler<IPointerClickHandler>(go);

    // Save the pending click state.
    pointerData.rawPointerPress = go;
    pointerData.eligibleForClick = true;
    pointerData.clickCount = 1;
    pointerData.clickTime = Time.unscaledTime;
    }
