### ISSUE TITLE
README file does not describe how to run the app.

### ISSUE THREAD

**Issue by andela-bojengwa** [googlesamples/io2015-codelabs#32]
There is no description of how to run the run/deploy the project. Would be nice to have a more detailed README that addresses this issue.

**Comment by keyboardsurfer** [comment]
This repository is a collection of code for the Google I/O 2015 codelabs, not a stand alone app.
Nonetheless it contains a handful of apps. Are you missing instructions how to run a single app within the repository?

**Comment by andela-bojengwa** [comment]
The AirHorn (https://github.com/GoogleChrome/airhorn) repo.

**Comment by keyboardsurfer** [comment]
Thanks for your reply. Please open this issue on the AirHorn repository.

**Comment by andela-bojengwa** [comment]
I think I clicked on the wrong issues link. Thank you @keyboardsurfer.
