### ISSUE TITLE
Building data-rich web apps with Lovefield - Link to the demo source code is missing in documentation

### ISSUE THREAD

**Issue by Cyberider** [googlesamples/io2015-codelabs#39]
The page missing the documentation link:
https://io2015codelabs.appspot.com/codelabs/lovefield

Look for this at the bottom of Step 1:
"The StockAnalyzer skeleton code (instructions on downloading available at “Step 0”)."

There is no "Step 0" and there is no hint as to where to find the "StockAnalylzer skeleton code". When I search the GH repo (via the link to reporting bugs) I do see the zip file for this missing data file.
https://github.com/googlesamples/io2015-codelabs/blob/master/lovefield/stock_analyzer.zip

**Comment by Cyberider** [comment]
Nevermind. This is NOT AN ISSUE.
I found it in:
"3. Step 0: Download and run the skeleton code"

**Comment by freshp86** [comment]
FWIW, you can also find the codelab at https://github.com/google/lovefield/blob/master/codelabs/stock_analyzer/docs/codelab.md, along with all the code.

**Comment by freshp86** [comment]
Closing since this is a non-issue, as stated in comment 2.
