### ISSUE TITLE
Duplicate LOC in ViewController.m example

### ISSUE THREAD

**Issue by lynnlangit** [googlesamples/io2015-codelabs#5]
Line 3 is duplicated (first LOC only) in the lab manual - it should only be entered once

3. Get the default GAITracker, and give it the value you set in the previous step
  id<GAITracker> tracker = [[GAI sharedInstance] defaultTracker];  id<GAITracker> tracker = [[GAI sharedInstance] defaultTracker];
 [tracker set:kGAIScreenName value:name];

**Comment by samthor** [comment]
This will be fixed in the next release, thanks!
