### ISSUE TITLE
doesn;t mention the "public" directory

### ISSUE THREAD

**Issue by johnwilkes** [googlesamples/io2015-codelabs#54]
the "firebase init" provided a set of prompts, for which I accepted the defaults. One of them was something about setting up a "public" directory (public).

Following along in at the next step, we're told to create an index.html - but apparently it needs to be in public/.

Send data to Firebase
Here is a HTML index.html page we will start with:
...

> firebase deploy
=== Deploying to 'resplendent-fire-2369'...
i  deploying hosting
i  preparing public directory for upload...
⚠  Warning: Public directory does not contain index.html
Error: Must have at least one file in public directory to deploy.

**Comment by hostirosti** [comment]
updated the codelab -> fixed
