### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by johnwilkes** [googlesamples/io2015-codelabs#55]
The first time I tried to run my test case, I got a console error: 
https://resplendent-fire-2369.firebaseapp.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

Also: it is disconcerting that the entered message typed into https://resplendent-fire-2369.firebaseapp.com/ vanishes when I press "POST" - but the value in the name field does not.

**Comment by hostirosti** [comment]
I added `<link rel="icon" href="data:;base64,iVBORw0KGgo=">` per http://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests to avoid the favicon.ico request.

We don't clear the name field on "POST" by design.
