### ISSUE TITLE
Remove [entire app] dialog is confusing

### ISSUE THREAD

**Issue by johnwilkes** [googlesamples/io2015-codelabs#56]
When I click on the red "X" in the topmost data item in my dashboard, I'm asked
     Remove resplendent-fire-2369?
With a big red "Remove" button.  The only sane interpretation of this is that I am trying to delete the entire app - not this single data item.  Not encouraging!

**Comment by hostirosti** [comment]
Hi John,
please send Firebase related feedback to https://groups.google.com/forum/#!forum/firebase-talk.

**Comment by johnwilkes** [comment]
done.
