### ISSUE TITLE
6. Authenticate users: a bunch of issues from the new cloud console

### ISSUE THREAD

**Issue by johnwilkes** [googlesamples/io2015-codelabs#58]
The instructions say to go to "APIs & Auth", but that's been renamed to "API manager".
When you get there, there is no "Create new client ID". You probably mean "New credentials" > "OAuth client ID", which does have "Web client" as one option.

There is no [click to] "Configure consent screen".  (Steps 6, 7, 9 are broken/out of order.)

Maybe "Open a new browser tab" should probably be "Open a new, anonymous browser tab"?  If not, it's not clear why it's needed.  Anyway - that prompts an entire Google SSO login.

After filling in the secret, it seems you need to clock in a different field to provoke the "Saved" popup.

Later on, after deploying the new code from this step, I follow the instructions, and get prompted to allow "Project Default Service Account would like to ..." which is somewhat alarming.  Where did that name come from?  I had called this "firebase test app".

Also, at this point I have two text boxes for posting messages, not the one shown in the examples.  (The lack of context in the copy-and-paste code is probably to blame here.)

**Comment by hostirosti** [comment]
"The instructions say to go to "APIs & Auth", but that's been renamed to "API manager".
When you get there, there is no "Create new client ID". You probably mean "New credentials" > "OAuth client ID", which does have "Web client" as one option."
updated

"There is no [click to] "Configure consent screen". (Steps 6, 7, 9 are broken/out of order.)"
corrected

"After filling in the secret, it seems you need to clock in a different field to provoke the "Saved" popup." not needed, it's immediately saved after pasting in.

"Later on, after deploying the new code from this step, I follow the instructions, and get prompted to allow "Project Default Service Account would like to ..." which is somewhat alarming. Where did that name come from? I had called this "firebase test app"."
Wasn't able reproduce what you see here.

"Also, at this point I have two text boxes for posting messages, not the one shown in the examples. (The lack of context in the copy-and-paste code is probably to blame here.)"
Not sure why you end up with "two" text boxes. The instructions describe to replace the username input box with a login button. There are no instructions for adding a second text box. As a side note: the codelab is not intend to be c&p only.
