### ISSUE TITLE
app-indexing "3: Run the sample app" needs step 2 "Select gradle-wrapper.properties"

### ISSUE THREAD

**Issue by dbs** [googlesamples/io2015-codelabs#6]
Step 2 says "Click the Gradle sync button." but the Gradle sync button is disabled until the gradle-wrapper.properties file under Gradle Scripts is selected.

**Comment by samtstern** [comment]
I think that may be a coincidence.  The gradle sync button becomes enabled when Android Studio finishes "Indexing" the source, which could take a few minutes.  I will close this issue and add a note about this.
