### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by ahmed14642** [googlesamples/io2015-codelabs#60]
i did exactly wat u did but it shows this error when i try to add book

**Comment by keyboardsurfer** [comment]
This is a collection of codelabs. Which codelab exactly are you referring to?

**Comment by ahmed14642** [comment]
cloud-nodejs

**Comment by beccasaurus** [comment]
See up-to-date codelab:
https://github.com/googlecodelabs/cloud-nodejs
