### ISSUE TITLE
Step 8 of 'Building a gRPC service with Node.js - incomplete command 

### ISSUE THREAD

**Issue by lynnlangit** [googlesamples/io2015-codelabs#9]
The first time the student runs the node client the command is shown as below:

$ node client.js

In order to produce the result shown in the screenshot shown below:

{ books: 
   [ { id: 123,
       title: 'A Tale of Two Cities',
       author: 'Charles Dickens' } ] }

The command should be as follows:

$ node client.js list

**Comment by samtstern** [comment]
Thanks for the report!  Just made the fix, pushing to production.
