### ISSUE TITLE
Code for Offline Application is missing

### ISSUE THREAD

**Issue by EdricChan03** [googlesamples/io2015-codelabs#99]

**Comment by websiteuno** [comment]
All the code and download files are missing from the page. It shows things like "Use this code:" and there is no code.

**Comment by jhall39** [comment]
I was going to open an issue about this as well. I believe we're all talking about this page: https://developers.google.com/web/fundamentals/getting-started/codelabs/offline/
At least, that's where I'm seeing the issue.

**Comment by billhimmelsbach** [comment]
Just going to throw my complaint on the pile. Missing a few code blocks from the tutorial, pics below.

<img width="872" alt="screen shot 2016-10-17 at 2 54 32 pm" src="https://cloud.githubusercontent.com/assets/19983248/19457130/b3a0cd6a-9479-11e6-968c-e16b9e22ebb1.png">
<img width="851" alt="screen shot 2016-10-17 at 2 54 48 pm" src="https://cloud.githubusercontent.com/assets/19983248/19457131/b903985a-9479-11e6-9693-8909c037d5a5.png">

**Comment by glrodasz** [comment]
I'm having the same issue.

**Comment by SimonPatis** [comment]
This does not seem to be updated yet, still missing code blocks

**Comment by hagata** [comment]
Can't seem to find where (if anywhere) to make a PR, but it looks like the following code blocks are what are missing. 

For the missing step,
> _Add the following code to the bottom of your sw.js to log the requests made from the parent page._
```
self.addEventListener('fetch', event => {
  console.log('Request:', event.request.url)
})
```

Modify that in the next missing step, 
> To make your application work offline you need to pull the request from the cache, if it is available.

> Update your fetch event listener to match the code below._
```
self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(response => {
      return response || fetch(event.request);
    })
  );
});
```

**Comment by SimonPatis** [comment]
Thanks @hagata  
I will attempt to implement your suggestion. 👍

**Comment by EdricChan03** [comment]
Looks like the code blocks were added!
